@startuml BaseEntities

class Excercise {
    + Id 
    + Level
    + Description 
    + Muscle 
    + SecondaryMuscle 
}

interface Equipmentable{
    + Equipment
}

class DurationableExcercise{

}

class RepeatableExcercise {

}

class EquipmentableDurationableExcercise {

}

class EquipmentableRepeatableExcercise {

}

class Weight {
    - Mass 
    + GetMass()
}

class Machine{
}

class Equipment {
    + Name
}

class User {
    - _sex : int 
    - _weight : double 
    - _height : double 
    - _name : String 
}

class WorkoutHistory {
    id : int
    date : String 
    muscleGroup : String
    excerciseList : String
    isDone : bool 
}

DurationableExcercise <|-- Excercise
RepeatableExcercise <|-- Excercise


EquipmentableDurationableExcercise <|-- DurationableExcercise
EquipmentableRepeatableExcercise <|-- RepeatableExcercise

EquipmentableDurationableExcercise <|.. Equipmentable
EquipmentableRepeatableExcercise <|.. Equipmentable

Machine <|-- Equipment
Weight <|-- Equipment
@enduml 