@startuml UserWorkout

class User {
    - _sex : int 
    - _weight : double 
    - _height : double 
    - _name : String 
}

class WorkoutHistory {
    id : int
    date : String 
    muscleGroup : String
    excerciseList : String
    isDone : bool 
}

abstract class IHistoryRepo {
    + saveHistory(workout: WOrkoutHistory): Future<void>
    + getHistory(id: int): Future<WorkoutHistory?>
}

IHistoryRepo ..> WorkoutHistory

@enduml