// Mocks generated by Mockito 5.4.6 from annotations
// in workout_planner/test/Feature/Domain/UseCases/Workout/workout_persistence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workout_planner/Features/Domain/Entities/Workout/workout.dart'
    as _i4;
import 'package:workout_planner/Features/Domain/Repository/history_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IHistoryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHistoryRepo extends _i1.Mock implements _i2.IHistoryRepo {
  MockIHistoryRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> saveWorkout(_i4.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkout, [workout]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i4.Workout?> getWorkout(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkout, [id]),
            returnValue: _i3.Future<_i4.Workout?>.value(),
          )
          as _i3.Future<_i4.Workout?>);

  @override
  _i3.Future<void> deleteWorkout(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> updateWorkout(_i4.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workout]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Workout>> getByDate(DateTime? date, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getByDate, [date], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i3.Future<List<_i4.Workout>>);

  @override
  _i3.Future<List<_i4.Workout>> getBeforeDate(DateTime? date, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getBeforeDate, [date], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i3.Future<List<_i4.Workout>>);

  @override
  _i3.Future<List<_i4.Workout>> getAfterDate(DateTime? date, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getAfterDate, [date], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i3.Future<List<_i4.Workout>>);

  @override
  _i3.Future<List<_i4.Workout>> getAll({
    int? limit,
    bool? newestFirst = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #limit: limit,
              #newestFirst: newestFirst,
            }),
            returnValue: _i3.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i3.Future<List<_i4.Workout>>);
}
